config/routes.rb
KanguruApp::Application.routes.draw do
  root to: "CurrentRecommendations#destination"
  
  get "recommendation" => "CurrentRecommendations#index", :as => "recommendation"
  post "recommendation" => "CurrentRecommendations#index", :as => "recommendation"
  
  get "test" => "CurrentRecommendations#test"
end

app/models/conditional_item.rb
class ConditionalItem < ActiveRecord::Base
  attr_accessible :transportation_id, :image, :name
  
  belongs_to :transportation
end

app/models/current_weather.rb
class CurrentWeather < ActiveRecord::Base
  # This model will just pull a forecast. I may actually hook the data up to a database later.
  attr_accessible :temperature, :wind_speed, :humidity, :condition, :wind_direction, :city, :state, :json_data
  
  require 'open-uri'
  require 'json'
  
  attr_accessor :forecast_json
  
  before_validation :import_data
  
  def import_data
    # Should allow for cases of entered data
    self.city = "Chicago"
    self.state = "IL"
    
    self.json_data = open("http://api.wunderground.com/api/010d8d7c9ed487d9/geolookup/hourly/conditions/forecast/q/#{state}/#{city}.json").read
    
    @forecast_json = JSON.parse(json_data)
    
    self.temperature = @forecast_json["current_observation"]["temp_f"].to_i
    self.wind_speed = @forecast_json["current_observation"]["wind_mph"].to_i
    self.humidity = @forecast_json["current_observation"]["relative_humidity"]
    self.condition = @forecast_json["current_observation"]["weather"]
    self.wind_direction = @forecast_json["current_observation"]["wind_dir"]
  end
  
end

app/models/forecast.rb
class Forecast
  # This model will just pull a forecast. I may actually hook the data up to a database later.
  
  require 'open-uri'
  require 'json'
  
end

app/models/transportation.rb
class Transportation < ActiveRecord::Base
  attr_accessible :condition, :image, :name
  
  has_many :conditional_items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/current_recommendations_controller.rb
class CurrentRecommendationsController < ApplicationController
  def index
    if CurrentWeather.where("created_at > ?", 1.hour.ago).count > 0
      @weather = CurrentWeather.where("created_at > ?", 1.hour.ago).order("created_at DESC").limit(1)[0]
    else
      @weather = CurrentWeather.create
    end
    
    if params[:destination]
      @destination = params[:destination]
    else
      @destination = ""
    end
    
  end
  
  def destination
    latitude = cookies[:lat]
    longitude = cookies[:lon]

    def split(a)
        b = "%.3f" % a
        return b
    end

    @lat_string = split(latitude.to_f).to_s
    @lon_string = split(longitude.to_f).to_s

    @lat = @lat_string
    @lon = @lon_string

    # @lat = cookies[:lat].to_f
    # @lon = cookies[:lon].to_f
    @acc = cookies[:acc]
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/current_recommendations_helper.rb
module CurrentRecommendationsHelper
  
  def condition_class(current_weather)
    
    if current_weather.condition.downcase.match('rain') || current_weather.condition.downcase.match('drizzle')  || current_weather.condition.downcase.match('mist') 
      return "rain"
    elsif current_weather.condition.downcase.match('sun') || current_weather.condition.downcase.match('cloud')
      return "sunny"
    elsif current_weather.condition.downcase.match('snow')
      return "snow"
    elsif current_weather.condition.downcase.match('overcast')
      return "overcast"
    # else
      # return "sunny"
    end
    
  end
  
  def recommended_transportation(current_weather)
    
    @my_conditon = condition_class(current_weather)
    
    if @my_conditon == "rain"
      return "car"
    elsif @my_conditon == "sunny" || @my_conditon == "overcast"
      return "bike"
    else
      return "train"
    end
    
  end
  
  def condition_img(current_weather)
    
    if current_weather.condition.downcase.match('rain') || current_weather.condition.downcase.match('drizzle')  || current_weather.condition.downcase.match('mist') 
      return "/assets/backgrounds/rainy-bg.jpg"
    elsif current_weather.condition.downcase.match('sun') || current_weather.condition.downcase.match('cloud')
      return "/assets/backgrounds/sunny-bg.jpg"
    elsif current_weather.condition.downcase.match('snow')
      return "/assets/backgrounds/snowing-bg.jpg"
    elsif current_weather.condition.downcase.match('overcast')
      return "/assets/backgrounds/overcast-bg.jpg"
    elsif current_weather.condition.downcase.match('clear')
      return "/assets/backgrounds/clear-night-bg.jpg"
    # else
      # return "sunny"
    end
    
  end
  
end

app/views/current_recommendations/destination.html.erb
<% content_for :body_attributes, "class=destination" %>

<div class="wrapper">

  <header>
  	<!-- LOGO -->
  	<div class="logo">
    	<img src="/assets/kangurulogo01.png" alt="Kanguru App">
  	</div>
  	<!-- END LOGO -->
  </header>

  <%= form_tag(recommendation_url) do |f| %>
    <p><%= label_tag "current_location", "starting location" %>
    <%= text_field_tag "current_location", "Current Location" %><button id="geo_location" onclick="getGeoLocation();" ></button></p>
  
    <p><%= label_tag "Destination", "destination" %>
    <input type="text" name="destination" required></p>
    
    <p class="submission">
      <%= button_tag "go!", :type => "submit", :class => "btn-go" %>
      <button id="skip">skip</button>
    </p>
  <% end %>

</div>

app/views/current_recommendations/index.html.erb
<% content_for :body_attributes, "class=weather_recommendation" %>

<div class="wrapper">

	<!-- BACKGROUND WRAPPER -->
	<div class="background <%# condition_class @weather %>"> 

			<!-- HEADER/NAV BAR -->
		<header>
		  <div class="container">
  			<nav>
  				<ol>
  					<li class="route"><a href="https://maps.google.com/maps?daddr=<%= CGI.escape(@destination) %>&saddr=222+Merchandise+Mart+Plaza,+Chicago,+IL&hl=en&sll=41.889819,-87.631888&sspn=0.018498,0.038581&geocode=FWlMgAId4VfG-imJ3MoOMdIPiDFl0ctY20sVJw%3BFXEqfwIdXMrG-ilx0yL7tiwOiDF1y_qieOluxQ&oq=222+West+Merchandise+Mart+Plaza&mra=ls&t=m&z=12">Route Pin</a></li>
  					<li class="destination"><a href="https://maps.google.com/maps?daddr=<%= CGI.escape(@destination) %>&saddr=222+Merchandise+Mart+Plaza,+Chicago,+IL&hl=en&sll=41.889819,-87.631888&sspn=0.018498,0.038581&geocode=FWlMgAId4VfG-imJ3MoOMdIPiDFl0ctY20sVJw%3BFXEqfwIdXMrG-ilx0yL7tiwOiDF1y_qieOluxQ&oq=222+West+Merchandise+Mart+Plaza&mra=ls&t=m&z=12" class="confirm_exit">
  					<% if @destination.blank? %>
  					  Map your route
  					<% else %>
  					  <%= @destination %>
  					<% end %></a>
  					</li>
  					<li class="home"><a href="<%= root_path %>" selected>Home</a></li>
  				</ol>
  			</nav>
			</div>
		</header>
    
    <div class="container">
  		<!-- DAY DESCRIPTION -->
  		<div class="day_desc">
  			<p class="desc_info"><%= @weather.condition %></p>
  		</div>
  		<!-- DAY DESCRIPTION END -->

  		<!-- WEATHER INFO -->
  		<article class="weather-container">
  			<div class="weather">
  				<p class="temperature">
  					<%= @weather.temperature %>&deg;
  				</p>
  			</div>
  			<div class="weather">
  				<p class="percipitation">
  					<%= @weather.humidity %> humidity
  				</p>
  				<p class="wind">
  					<%= @weather.wind_direction %> <%= @weather.wind_speed %>mph
  				</p>
  			</div>
  		</article>
  		<!-- WEATHER INFO END -->
		</div>
		
		<!-- Recommendations -->
		<div id="recommendations" class="<%= recommended_transportation @weather %>">
				<section class="recommendation car">
				  
					<div class="transportation">
					  <div class="btn-right"></div>
						<h3><span class="best">Best</span> Option</h3>
						<img src="/assets/mode_car.png" alt="car" />
					</div>
					<img src="/assets/rounded-top.png" class="transport_bg">
					<div class="items">
						<h3>Bring That</h3>
						<ul>
							<li>
								<img src="/assets/car/boot.png" alt="boot" />
								<div class="caption">boot</div>
							</li>
							<li>
								<img src="/assets/car/coffee.png" alt="coffee" />
								<div class="caption">coffee</div>
							</li>
							<li>
								<img src="/assets/car/donut.png" alt="donut" />
								<div class="caption">donut</div>
							</li>
							<li>
								<img src="/assets/car/jacket.png" alt="jacket" />
								<div class="caption">jacket</div>
							</li>
							<li>
								<img src="/assets/car/podcast.png" alt="podcast" />
								<div class="caption">podcast</div>
							</li>
							<li>
								<img src="/assets/car/umbrella.png" alt="umbrella" />
								<div class="caption">umbrella</div>
							</li>
						</ul>
					</div>
				</section>

				<section class="recommendation train">
				  
					<div class="transportation">
					  <div class="btn-left"></div>
  				  <div class="btn-right"></div>
						<h3><span class="best">Best</span> Option</h3>
						<img src="/assets/train/mode_train.png" alt="train" />
					</div>
					<img src="/assets/rounded-top.png" class="transport_bg">
					<div class="items">
						<h3>Bring That</h3>
						<ul>
							<li>
								<img src="/assets/train/book.png" alt="book" />
								<div class="caption">book</div>
							</li>
							<li>
								<img src="/assets/train/boot.png" alt="boot" />
								<div class="caption">boot</div>
							</li>
							<li>
								<img src="/assets/train/coffee.png" alt="coffee" />
								<div class="caption">coffee</div>
							</li>
							<li>
								<img src="/assets/train/gloves.png" alt="gloves" />
								<div class="caption">gloves</div>
							</li>
							<li>
								<img src="/assets/train/hat.png" alt="hat" />
								<div class="caption">hat</div>
							</li>
							<li>
								<img src="/assets/train/mace.png" alt="mace" />
								<div class="caption">mace</div>
							</li>
						</ul>
					</div>
				</section>

				<section class="recommendation bike">
				  
					<div class="transportation">
					  <div class="btn-left"></div>
						<h3><span class="best">Best</span> Option</h3>
						<img src="/assets/bike/mode_bike.png" alt="car" />
					</div>
					<img src="/assets/rounded-top.png" class="transport_bg">
					<div class="items">
						<h3>Bring That</h3>
						<ul>
							<li>
								<img src="/assets/bike/helmet.png" alt="helmet" />
								<div class="caption">helmet</div>
							</li>
							<li>
								<img src="/assets/bike/music.png" alt="music" />
								<div class="caption">music</div>
							</li>
							<li>
								<img src="/assets/bike/shirt.png" alt="shirt" />
								<div class="caption">extra shirt</div>
							</li>
							<li>
								<img src="/assets/bike/sun-screen.png" alt="sunscreen" />
								<div class="caption">sunscreen</div>
							</li>
							<li>
								<img src="/assets/bike/sunglasses.png" alt="sunglasses" />
								<div class="caption">sunglasses</div>
							</li>
							<li>
								<img src="/assets/bike/water.png" alt="water" />
								<div class="caption">water</div>
							</li>
						</ul>
					</div>
				</section>
			</div>
		<!-- Recommendations END -->
		
		
	</div>
	<!-- BACKGROUND WRAPPER END -->
</div>

<script>
  $(document).ready(function(){
    $.backstretch("<%= condition_img @weather %>");
  });
</script>

app/views/current_recommendations/test.html.erb
<div class="container">
  <div id="recommendations" class="car">
    <section class="recommendation car">
      <div class="transportation">
        <h3>Best Option</h3>
        <img src="/assets/mode_car.png" alt="car" />
      </div>
      <img src="/assets/rounded-top.png" class="transport_bg">
      <div class="items">
        <h3>Bring That</h3>
        <ul>
          <li>
            <img src="/assets/car/boot.png" alt="boot" />
            <div class="caption">boot</div>
          </li>
          <li>
            <img src="/assets/car/coffee.png" alt="coffee" />
            <div class="caption">coffee</div>
          </li>
          <li>
            <img src="/assets/car/donut.png" alt="donut" />
            <div class="caption">donut</div>
          </li>
          <li>
            <img src="/assets/car/jacket.png" alt="jacket" />
            <div class="caption">jacket</div>
          </li>
          <li>
            <img src="/assets/car/podcast.png" alt="podcast" />
            <div class="caption">podcast</div>
          </li>
          <li>
            <img src="/assets/car/umbrella.png" alt="umbrella" />
            <div class="caption">umbrella</div>
          </li>
        </ul>
      </div>
    </section>

    <section class="recommendation train">
      <div class="transportation">
        <h3>Best Option</h3>
        <img src="/assets/train/mode_train.png" alt="train" />
      </div>
      <img src="/assets/rounded-top.png" class="transport_bg">
      <div class="items">
        <h3>Bring That</h3>
        <ul>
          <li>
            <img src="/assets/train/book.png" alt="book" />
            <div class="caption">book</div>
          </li>
          <li>
            <img src="/assets/train/boot.png" alt="boot" />
            <div class="caption">boot</div>
          </li>
          <li>
            <img src="/assets/train/coffee.png" alt="coffee" />
            <div class="caption">coffee</div>
          </li>
          <li>
            <img src="/assets/train/gloves.png" alt="gloves" />
            <div class="caption">gloves</div>
          </li>
          <li>
            <img src="/assets/train/hat.png" alt="hat" />
            <div class="caption">hat</div>
          </li>
          <li>
            <img src="/assets/train/mace.png" alt="mace" />
            <div class="caption">mace</div>
          </li>
        </ul>
      </div>
    </section>

    <section class="recommendation bike">
      <div class="transportation">
        <h3>Best Option</h3>
        <img src="/assets/bike/mode_bike.png" alt="car" />
      </div>
      <img src="/assets/rounded-top.png" class="transport_bg">
      <div class="items">
        <h3>Bring That</h3>
        <ul>
          <li>
            <img src="/assets/bike/helmet.png" alt="helmet" />
            <div class="caption">helmet</div>
          </li>
          <li>
            <img src="/assets/bike/music.png" alt="music" />
            <div class="caption">music</div>
          </li>
          <li>
            <img src="/assets/bike/shirt.png" alt="shirt" />
            <div class="caption">extra shirt</div>
          </li>
          <li>
            <img src="/assets/bike/sun-screen.png" alt="sunscreen" />
            <div class="caption">sunscreen</div>
          </li>
          <li>
            <img src="/assets/bike/sunglasses.png" alt="sunglasses" />
            <div class="caption">sunglasses</div>
          </li>
          <li>
            <img src="/assets/bike/water.png" alt="water" />
            <div class="caption">water</div>
          </li>
        </ul>
      </div>
    </section>
  </div>
</div>






	<div class="variables">
	<!-- TRANSPORT -->
	<article class="transport-container">
		
		<!-- CHANGE TRANS BUTTONS -->
		<div class="othertrans">
			<button class="btn-left">Left</button>
			<button class="btn-right">Right</button>
		</div>
		<!-- CHANGE TRANS BUTTONS END -->

		<%= image_tag "mode_car.png", :alt => "Get off your lazy ass and bike", :class => "transport car" %>
	</article>
	<!-- TRANSPORT END -->
	

	<!-- ITEMS -->
	<footer>
		<p>BRING THAT</p>
		<%= image_tag "car_icons_boot.png", :class => "item" %>
		<%= image_tag "car_icons_coffee.png", :class => "item" %>
		<%= image_tag "car_icons_donut.png", :class => "item" %>
		<%= image_tag "car_icons_jacket.png", :class => "item" %>
		<%= image_tag "car_icons_podcast.png", :class => "item" %>
		<%= image_tag "car_icons_umbrella.png", :class => "item" %>
	</footer>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>KanguruApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="initial-scale=1, maximum-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes" /> 
  <meta name="apple-touch-fullscreen" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  <link rel="shortcut icon" href="favicon.ico" />
  <link rel="apple-touch-icon" href="apple-touch-icon.png" />
  <link rel="apple-touch-icon" sizes="72x72" href="apple-touch-icon-72x72.png" />
  <link rel="apple-touch-icon" sizes="114x114" href="apple-touch-icon-114x114.png" />

  <%- unless @lat %>
    <script>
      getGeoLocation();
    </script>
  <%- end %>
  <script type="text/javascript">
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-32982442-1']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
  </script>
</head>
<body <%= yield :body_attributes %>>

<%= yield %>

</body>
</html>